# Generated by Django 3.0 on 2020-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200423_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('panel_size', models.CharField(max_length=500)),
                ('panel_holes_punch_qty', models.DecimalField(decimal_places=0, max_digits=500)),
                ('panel_holes_cut_qty', models.DecimalField(decimal_places=0, max_digits=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
