# Generated by Django 3.0 on 2020-04-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200423_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='panel_size',
            field=models.CharField(choices=[('NO_PANEL', 'No Panel'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='No Panel', max_length=10),
        ),
    ]
