# Generated by Django 3.0 on 2020-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200429_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='part_number',
            field=models.CharField(default='P/N:', max_length=500),
        ),
    ]
